version: '3.1'
services:
  inteliview:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/config/config.env
    ports:
      - 3000:3000

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - inteliview
    
